### ISSUE TITLE
Trailing space on country name

### ISSUE THREAD

**Issue by Jamesking56** [squirephp/squire#22]
**Describe the bug**
There is a trailing space at the end of the country `Bonaire, Saint Eustatius and Saba` so that is displays as `"Bonaire, Saint Eustatius and Saba "`

**To reproduce**
Pull in the code and view the country above, notice the extra space that appears at the end.

**Expected behavior**
No trailing spaces in countries.

**Context**
- Squire version: `squirephp/countries-en` `v2.0.5`
- Laravel version: `8.25.0`
- Server OS: N/A
- PHP version: `8.0`

**Additional details**
Looks like its in the CSV file

**Comment by danharrin** [comment]
Fixed, thank you!
