### ISSUE TITLE
[BUG]  could not find driver (SQL: select * from "countries" order by "name" asc)

### ISSUE THREAD

**Issue by sayandeep-volition** [squirephp/squire#29]
**Describe the bug**
Installed the package then when I was going to use it in the blade that time I got this error.

**To reproduce**
`  @foreach (Squire\Models\Country::orderBy('name')->get() as $country)
                                            <option value="{{ $country->id }}">{{ $country->name }} {{ $country->flag }}</option>
                                        @endforeach`
**Expected behavior**
All country list

**Context**
- squirephp/countries-en: 2.1
- Laravel/framework:  8.40"
- Windows 10
- PHP 7.4

**Additional details**

Did I skip any steps?

**Comment by danharrin** [comment]
Hey, do you have the SQLite extension installed for PHP?
