### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by Odilbukh** [squirephp/squire#58]
**Describe the bug**
When I run command "composer require squirephp/currencies" to install it returns error (see screenshots)  

**To reproduce**
A simplified code example to demonstrate the issue you are facing.

**Expected behavior**

**Context**
- Squire version: 3.3
- Laravel version: 9.50.2 
- Server OS:  Ubuntu 22.04.4
- PHP version: 8.1 (on my computer), "^8.0.2" on file composer.json

**Additional details**
![image](https://user-images.githubusercontent.com/22895615/217477264-4050691d-96eb-4997-b5e4-7d27f14d7014.png)
![image](https://user-images.githubusercontent.com/22895615/217477351-971ad0ee-49fc-4c84-9a3a-1731ef52ad86.png)

**Comment by danharrin** [comment]
You need to enable PHP's `pdo_sqlite` extension

**Comment by Odilbukh** [comment]
> o enable PHP's `pdo_sqlite` extension

But it's already enabled

![image](https://user-images.githubusercontent.com/22895615/217501606-b841c4b1-57ff-4fef-8a05-b15edd7018d6.png)

**Comment by danharrin** [comment]
Read the error message, your command line version of PHP doesn't have it

**Comment by Odilbukh** [comment]
ok!

**Comment by Odilbukh** [comment]
does the package work with PHP 8.1 ?

**Comment by danharrin** [comment]
Yes
