### ISSUE TITLE
Can not disply flag in chrome or chrome based browser

### ISSUE THREAD

**Issue by fftfaisal** [squirephp/squire#87]
I use this csv file and import into my db countries.sql

https://github.com/squirephp/squire/blob/3.x/packages/countries-en/resources/data.csv

which is working fine in firefox. It can display flag. But when I tried in chrome it just display as text. I thought it may causes I imported into mysql incorrectly but it seems something is happening with data. I attached both screenshot

# Firefox

## In Repo
![image](https://github.com/user-attachments/assets/a8e466d9-01c1-4c37-982d-f63c591b2590)

## In my project
![image](https://github.com/user-attachments/assets/18e82867-8b08-4197-a8b7-0cba7382d3c9)

# Chrome

## In Repo
![image](https://github.com/user-attachments/assets/9b663d25-ecd4-4cbd-bd39-c4c9ca61325f)

## In my project
![image](https://github.com/user-attachments/assets/675e4e52-a496-4150-b145-40a742000eef)

**Comment by danharrin** [comment]
We are just using emojis here, so it's however your browser/system renders flag emojis. I am also using Chrome, but they render fine on MacOS. There isn't anything we can do here unfortunately.

<img width="1624" alt="Screenshot 2024-09-20 at 08 55 27" src="https://github.com/user-attachments/assets/28f371f8-5677-4674-b9f0-06dbb7fd4397">

**Comment by fftfaisal** [comment]
It seems problem in windows system. I also checked in other windows computer, which also have same issue on chrome.

**Comment by danharrin** [comment]
You will have to find an image-based flag set then, we just use emojis for simplicity as they usually work.

**Comment by danharrin** [comment]
https://www.reddit.com/r/chrome/comments/7gc9kp/help_flag_emojis_dont_show_up_in_chrome/

**Comment by fftfaisal** [comment]
> https://www.reddit.com/r/chrome/comments/7gc9kp/help_flag_emojis_dont_show_up_in_chrome/

Thanks man. It solved the problem.
